// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9lhZ-RQQlpC507jJ7KcU-BYBU20J0BAs',
    appId: '1:328551992610:web:3ba8d79586fcec46fe697b',
    messagingSenderId: '328551992610',
    projectId: 'musahi-app',
    authDomain: 'musahi-app.firebaseapp.com',
    storageBucket: 'musahi-app.firebasestorage.app',
    measurementId: 'G-0RD43Y6P16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_xu-3MtE0J4mwE8P2scoOO4jhqLXpXA',
    appId: '1:328551992610:android:ef03ea4d392aba35fe697b',
    messagingSenderId: '328551992610',
    projectId: 'musahi-app',
    storageBucket: 'musahi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKh8VhNQsuIYy4ZTC1z8TagvmQIJ7UN8o',
    appId: '1:328551992610:ios:b71b92dceccc5457fe697b',
    messagingSenderId: '328551992610',
    projectId: 'musahi-app',
    storageBucket: 'musahi-app.firebasestorage.app',
    iosBundleId: 'com.example.musahi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKh8VhNQsuIYy4ZTC1z8TagvmQIJ7UN8o',
    appId: '1:328551992610:ios:b71b92dceccc5457fe697b',
    messagingSenderId: '328551992610',
    projectId: 'musahi-app',
    storageBucket: 'musahi-app.firebasestorage.app',
    iosBundleId: 'com.example.musahi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9lhZ-RQQlpC507jJ7KcU-BYBU20J0BAs',
    appId: '1:328551992610:web:c6734d4591e9609bfe697b',
    messagingSenderId: '328551992610',
    projectId: 'musahi-app',
    authDomain: 'musahi-app.firebaseapp.com',
    storageBucket: 'musahi-app.firebasestorage.app',
    measurementId: 'G-HFTTXNPNKS',
  );
}
